#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4E7160ED4AC8EE1D (michael@stapelberg.de)
#
Name     : i3status
Version  : 2.13
Release  : 7
URL      : https://i3wm.org/i3status/i3status-2.13.tar.bz2
Source0  : https://i3wm.org/i3status/i3status-2.13.tar.bz2
Source1 : https://i3wm.org/i3status/i3status-2.13.tar.bz2.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: i3status-bin = %{version}-%{release}
Requires: i3status-data = %{version}-%{release}
Requires: i3status-license = %{version}-%{release}
Requires: i3status-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : libnl-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(libconfuse)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : xmlto
BuildRequires : yajl-dev

%description
# i3status
## Description
i3status is a small program for generating a status bar for i3bar, dzen2, xmobar
or similar programs. It is designed to be very efficient by issuing a very small
number of system calls, as one generally wants to update such a status line
every second. This ensures that even under high load, your status bar is updated
correctly. Also, it saves a bit of energy by not hogging your CPU as much as
spawning the corresponding amount of shell commands would.

%package bin
Summary: bin components for the i3status package.
Group: Binaries
Requires: i3status-data = %{version}-%{release}
Requires: i3status-license = %{version}-%{release}

%description bin
bin components for the i3status package.


%package data
Summary: data components for the i3status package.
Group: Data

%description data
data components for the i3status package.


%package license
Summary: license components for the i3status package.
Group: Default

%description license
license components for the i3status package.


%package man
Summary: man components for the i3status package.
Group: Default

%description man
man components for the i3status package.


%prep
%setup -q -n i3status-2.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565219731
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-builddir
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1565219731
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/i3status
cp LICENSE %{buildroot}/usr/share/package-licenses/i3status/LICENSE
%make_install
## install_append content
install -d -m 755 %{buildroot}/usr/share/xdg/i3status
install -m 644 i3status.conf %{buildroot}/usr/share/xdg/i3status/config
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/i3status

%files data
%defattr(-,root,root,-)
/usr/share/xdg/i3status/config

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/i3status/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/i3status.1
